rosdistro: 'noetic

  '
roslaunch:
  uris:
    host_maxence_virtualbox__36431: http://maxence-VirtualBox:36431/
rosversion: '1.15.13

  '
run_id: fe4695b0-5c57-11ec-8913-0b07e35cc642
turtlesim:
  background_b: 255
  background_g: 86
  background_r: 150
